modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/TheMCBrothers/Pudding-Mod/issues"
license = "MIT License"

[[mods]]
modId = "puddingmod"
version = "${version}"
displayName = "Pudding Mod"
displayURL = "https://themcbrothers.net/mods/puddingmod"
authors = "TheMCLoveMan"
description = '''
Pudding in Minecraft!
'''
#logoFile = ""

[[dependencies.puddingmod]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.puddingmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.puddingmod]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.7,)"
ordering = "AFTER"
side = "BOTH"