modLoader = "javafml"
loaderVersion = "[49,)"
issueTrackerURL = "https://github.com/TheMCBrothers/Pudding-Mod/issues"
license = "MIT License"

[[mods]]
modId = "puddingmod"
version = "${version}"
displayName = "Pudding Mod"
displayURL = "https://themcbrothers.net/mods"
authors = "TheMCLoveMan"
description = '''
Pudding in Minecraft!
'''
logoFile = "pack.png"

[[dependencies.puddingmod]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.puddingmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.puddingmod]]
modId = "architectury"
mandatory = true
versionRange = "[11,)"
ordering = "AFTER"
side = "BOTH"