modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/TheMCBrothers/Pudding-Mod/issues"
license = "MIT License"

[[mods]]
modId = "puddingmod"
version = "${version}"
displayName = "Pudding Mod"
authors = "TheMCLoveMan"
description = '''
Pudding in Minecraft!
'''
#logoFile = ""

[[dependencies.puddingmod]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.puddingmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.puddingmod]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"