modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/TheMCBrothers/Pudding-Mod/issues"
license = "MIT License"

[[mods]]
modId = "puddingmod"
version = "${version}"
displayName = "Pudding Mod"
displayURL = "https://themcbrothers.net/mods"
authors = "TheMCLoveMan"
description = '''
Pudding in Minecraft!
'''
logoFile = "pack.png"
logoBlur = false

[[dependencies.puddingmod]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.puddingmod]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.puddingmod]]
modId = "architectury"
type = "required"
versionRange = "[11.1,)"
ordering = "AFTER"
side = "BOTH"